# Generated by Django 4.1 on 2022-08-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
